export enum DataTypes {
  FAISS = 'FAISS',
  MILVUS = 'MILVUS',
  PINECONE = 'PINECONE',
  WEAVIATE = 'WEAVIATE',
  QDRANT = 'QDRANT',
  REDIS_VECTOR = 'REDIS_VECTOR',
  NEO4J = 'NEO4J',
  POSTGRESQL_VECTOR = 'POSTGRESQL_VECTOR',
  H_2 = 'H_2'
}
