export enum DlAction {
  API_TOKEN = 'API_TOKEN',
  DOWNLOAD_LLM_JSON = 'DOWNLOAD_LLM_JSON',
  DOWNLOAD_LLM_MODEL = 'DOWNLOAD_LLM_MODEL',
  CREATE_DIRECTORY = 'CREATE_DIRECTORY',
  GENERATE_CHECKSUM = 'GENERATE_CHECKSUM'
}
